/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ColecaoController;
import controller.QuadrinhoController;
import java.text.ParseException;
import java.util.List;
import javax.swing.JOptionPane;
import model.Colecao;
import model.Quadrinho;

/**
 *
 * @author joaoe
 */
public class AlterarQuadrinhos extends javax.swing.JFrame {
    
    int linhaSelecionada;

    Quadrinho quadrinho;
    
    
    /**
     * Creates new form InserirQuadrinhos
     * @param linha
     */
    public AlterarQuadrinhos(int linha) {
        initComponents();
        this.linhaSelecionada = linha;
        ColecaoController colecaoC = new ColecaoController();
        List<Colecao> colecoes = colecaoC.listar();
        
        colecoes.forEach((c) -> {
            txtColecao.addItem(c.getNome());
        });
        
        QuadrinhoController quadrinhoC = new QuadrinhoController();
        List<Quadrinho> quadrinhos = quadrinhoC.listar();
        
        int cont = 0;
        for(Quadrinho q: quadrinhos){
            if(cont == linha){
                this.quadrinho = q;
                break;
            }
            cont++;
        }
        txtTitulo.setText(this.quadrinho.getTitulo());
        txtUrl.setText(this.quadrinho.getUrlCapa());
        txtAutor.setText(this.quadrinho.getAutor());
        txtQtdPaginas.setText(String.valueOf(this.quadrinho.getQtdPaginas()));
        txtSubtitulo.setText(this.quadrinho.getSubtitulo());
        txtSinopse.setText(this.quadrinho.getSinopse()); 
    }
    
    public AlterarQuadrinhos() {
        initComponents();
        ColecaoController colecaoC = new ColecaoController();
        List<Colecao> colecoes = colecaoC.listar();
        
        colecoes.forEach((c) -> {
            txtColecao.addItem(c.getNome());
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtUrl = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtQtdPaginas = new javax.swing.JTextField();
        txtSubtitulo = new javax.swing.JTextField();
        txtSinopse = new javax.swing.JTextField();
        txtColecao = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Alterar Quadrinho");

        jLabel2.setText("Título*");

        jLabel4.setText("urlCapa");

        jLabel5.setText("Autor*");

        jLabel6.setText("Qtd Páginas*");

        jLabel7.setText("Subtitulo");

        jLabel9.setText("Sinopse");

        jLabel10.setText("Coleção");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtColecao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL" }));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Alterar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel12.setText("obs: * campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(txtUrl)
                            .addComponent(txtAutor)
                            .addComponent(txtQtdPaginas)
                            .addComponent(txtSubtitulo)
                            .addComponent(txtSinopse)
                            .addComponent(txtColecao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQtdPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtColecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new Quadrinhos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if(camposObrigatoriosOk()){
            try{
                try {
                    TelaLogin.funcao.alterarQuadrinho(this.quadrinho.getNotaFiscal().getValor(),
                            pegarUrl(), txtAutor.getText(), Integer.parseInt(txtQtdPaginas.getText()),               
                            pegarSubtitulo(),this.quadrinho.getNotaFiscal().getDataCompra(), pegarSinopse(), txtTitulo.getText(), pegarIdColecao());
                
                    JOptionPane.showMessageDialog(this, "Quadrinho alterado com sucesso");
                    new Quadrinhos().setVisible(true);
                    this.dispose();
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Insira uma data no formato correto");
                }
                
            }catch(NumberFormatException  e){
                JOptionPane.showMessageDialog(this, "Insira um valor numérico válido");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios");
        }
   
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private Integer pegarIdColecao(){
        String colecao = txtColecao.getSelectedItem().toString();
        if(!colecao.equals("NULL")){
            ColecaoController colecaoC = new ColecaoController();
            List<Colecao> colecoes = colecaoC.listar();
            for(Colecao c: colecoes){
                if(c.getNome().equals(colecao)){
                    return c.getId();
                }
            }
        }
        
        return -1;
    }
    
    private String pegarSinopse(){
        if(txtSinopse.getText().equals(""))
            return null;
        return txtSinopse.getText();
    }
    
    private String pegarSubtitulo(){
        if(txtSubtitulo.getText().equals(""))
            return null;
        return txtSubtitulo.getText();
    }
    
    private String pegarUrl(){
        if(txtUrl.getText().equals(""))
           return null;
        return txtUrl.getText();
    }
    
    private boolean camposObrigatoriosOk() {
        
        if(txtTitulo.getText().equals(""))
            return false;
        
        if(txtAutor.getText().equals(""))
            return false;
        if(txtQtdPaginas.getText().equals(""))
            return false;
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JComboBox<String> txtColecao;
    private javax.swing.JTextField txtQtdPaginas;
    private javax.swing.JTextField txtSinopse;
    private javax.swing.JTextField txtSubtitulo;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    
}
